kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-demo-pvc
  namespace: ngnix-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
